# Generated by Django 3.1.3 on 2020-11-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('post_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('image_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainadmin.adminpost')),
            ],
        ),
    ]
