# Generated by Django 3.1.3 on 2020-11-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0002_imageposts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageposts',
            name='tag',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
