# Generated by Django 3.1.3 on 2020-11-26 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0007_statustable'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustable',
            name='date_of_change',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
