# Generated by Django 3.1.3 on 2020-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0008_statustable_date_of_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustable',
            name='status_from_user',
            field=models.CharField(default='Unlike', max_length=30),
        ),
    ]
