# Generated by Django 3.1.3 on 2020-11-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0009_statustable_status_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustable',
            name='action',
            field=models.BooleanField(default=True),
        ),
    ]
